services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      AIRFLOW_DB_PASSWORD: $AIRFLOW_DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./airflow/docker/airflow-pg-init.sh:/docker-entrypoint-initdb.d/airflow-init.sh
      - ./airflow/docker/airflow-pg-init.sql:/tmp/airflow-init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  airflow:
    build: ./docker
    restart: always
    ports:
      - 8080:8080
    environment:
      AIRFLOW_USERNAME: $AIRFLOW_USERNAME
      AIRFLOW_FIRSTNAME: $AIRFLOW_FIRSTNAME
      AIRFLOW_LASTNAME: $AIRFLOW_LASTNAME
      AIRFLOW_PASSWORD: $AIRFLOW_PASSWORD    
      AIRFLOW_EMAIL: $AIRFLOW_EMAIL 
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:$AIRFLOW_DB_PASSWORD@db/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: &tz Europe/Minsk
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: *tz
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    
    volumes:
      - ./airflow/dags:/root/airflow/dags
      - ./airflow/logs:/root/airflow/logs
      - ./airflow/config:/root/airflow/config
      - ./airflow/plugins:/root/airflow/plugins
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
